config/routes.rb
Rails.application.routes.draw do
  resources :comments , except: [:new]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  devise_for :users
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments , except: [:new]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  end

  root 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree order: 'created_at DESC'
  belongs_to :user
  belongs_to :link
  validates :body , presence: true , length: {maximum: 10000}
  #validate :user_quota, :on => :create
  private
    def user_quota
      if user.comments.today.count >= 5
        errors.add(:base,"Exceeds daily limit")
      end
    end
end

app/models/link.rb
require 'net/http'
class Link < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  has_many :comments
  before_validation :addhttp
  validates :title , presence: true , length: {minimum: 5, maximum:50}
  VALID_URL_REGEX = /^(http|https):\/\/?([a-z0-9]+)([-.]{1}[a-z0-9]+)([\/.]{1}[a-z0-9]+){1}$/
  validates :url, :presence => true, uniqueness: true, :uri => { :format => VALID_URL_REGEX, :multiline => true}


  private
  def addhttp
    unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
      self.url = "http://#{self.url}"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :downcase_email
  has_many :links
  validates :name , presence: true , length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email , presence: true , length: { maximum: 255 } , format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_many :comments do

    def today
      where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))
    end
  end
  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :reply]
  respond_to :html , :js
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.hash_tree
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(parent_id: params[:parent_id],link_id: params[:link_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    lid = params[:link_id] == nil ? params[:comment][:link_id] : params[:link_id]
    @link = Link.find(lid)

    if params[:comment][:parent_id].to_i > 0
      parent = @link.comments.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)

    else
      @comment = @link.comments.new(comment_params)
    end
    @comment.link_id = @link.id
    @comment.user = current_user


    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        logger.debug "ERROR"
        format.json { render :json => { :error => @comment.errors.full_messages}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @address = @comment.link_id
    respond_to do |format|
      if @comment.update(comment_params)
        #format.html { redirect_to link_url(@address), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.json { render :json => { :error => @comment.errors.full_messages}, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @address = @comment.link_id
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to link_url(@address), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  respond_to :html, :json

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
    respond_with(@links)
  end

  # GET /links/1
  # GET /links/1.json
  def show
    respond_with(@links)
  end

  # GET /links/new
  def new
    @link = current_user.links.build
    respond_with(@links)
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)
    flash[:notice] = 'Link was successfully created.' if @link.save
    respond_with(@link)

=begin
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    #@link = Link.find(params[:id])
    respond_with(@link) do |format|
      if @link.update(link_params)
        #flash[:notice] = 'Link was successfully updated.'
        #redirect_to @link
        format.html { redirect_to @link , notice: 'Link was successfully updated.'}
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end


=begin
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_with @link do |format|
      format.html {redirect_to links_url, notice: 'Link was successfully destroyed.'}
      format.json { head :no_content }
    end

=begin
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
=end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end

  def authorized_user
    @link = current_user.links.find_by(id: params[:id])
    redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
def comments_tree_for(comments)
  comments.map do |comment|
    render(comment) + (comment.children.size > 0 ? content_tag(:div , comments_tree_for(comment.children),class: "replies" ): nil)
  end.join.html_safe
end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment , class: "comments")%>
    <div class="comments_wrapper clearfix">
        <div class="pull-left">
            <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.name %></small>
                <% if user_signed_in? %>
                    <%=link_to link_new_comment_path(@link,comment),remote: true do%>
                        <small class="reply_post">Reply</small>
                    <% end%>
                    <% if comment.user == current_user%>
                        <%=link_to edit_comment_path(comment),remote: true do%>
                                <small id="edit_post_<%= comment.id %>">Edit</small>
                        <% end%>
                        <%= link_to comment_path(comment), method: :delete, data: { confirm: 'Are you sure?'} do%>
                            <small id="destroy_post_<%= comment.id %>">Destroy</small>
                        <%end%>
                    <%end%>
                <%end%>
            </p>


            <p id="lead_<%=comment.id%>" class="leading"><%= comment.body %></p>
            <br>
            <% if user_signed_in? %>
            <div id="replying_<%= comment.id%>">
            </div>
            <%end%>
        </div>

    </div>

app/views/comments/_form.html.erb
<%= form_for(@comment , remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :link_id %>
  </div>
    <%if @comment.errors[:body]%>
    <%= f.text_area :body , :class => ".field_with_errors"%>
      <%else%>
        <div class="field">
            <%= f.text_area :body %>
        </div>
    <%end%>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Comment', class: "btn btn-primary"  %>
      <button id="Cancel_<%=@comment.id%>" class="btn btn-primary">Cancel</button>
  </div>
<% end %>

app/views/comments/_replyform.html.erb
<%= simple_form_for [@link, Comment.new], remote: true do |f| %>
    <%= f.hidden_field :parent_id , value: id%>
    <%= f.hidden_field :link_id , value: linkid%>
    <div class="field">
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <br>
    <div class="reply_action">
    <%= f.submit "Reply", class: "btn btn-primary" %>
    <%= submit_tag "Cancel" ,:type => 'button' , id: "Cancel_reply" ,class: "btn btn-primary"%>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/edit.js.erb
$(function() {


    $('#lead_<%=@comment.id%>').html("<%= j (render 'form') %>");

    $('#Cancel_<%=@comment.id%>').click(function(){
        var lead = $('.edit_comment').parent().parent().find('.leading');
        var text_value = null;
        if(!$('.edit_comment #comment_body').val()){
            text_value = $('.edit_comment #comment_body').data('val');
        }else{
            text_value= $('.edit_comment #comment_body').val();
        }
        lead.html(text_value);
    });

    $('.edit_comment #comment_body').focusin(function(){
        $(this).data('val',$(this).val());
    });

    $('#edit_comment_<%=@comment.id%>').on("ajax:success", function(data){

        $('.actions input[type="submit"]').val('Edit Again');
        $('.actions input[type="submit"]').prop('disabled',false);
        $('#Cancel_<%=@comment.id%>').show();
        $('.errorz').remove();
    }).bind("ajax:send",function(){
        $('#Cancel_<%=@comment.id%>').hide();
        $('#lead_<%=@comment.id%> p').remove();
        $('.actions input[type="submit"]').val('Loading');
        $('.actions input[type="submit"]').prop('disabled',true);
    }).bind("ajax:error", function(e,xhr,status,error){
        $('#lead_<%=@comment.id%>').append($('<p> -'+xhr.responseJSON.error+ ' </p>').addClass('errorz'));
        $('.actions input[type="submit"]').val('Resubmit');
        $('.actions input[type="submit"]').prop('disabled',false);
        $('#Cancel_<%=@comment.id%>').show();
    });
});

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$(function(){

    $('#replying_<%= @comment.parent_id%>').html("<%= j (render 'replyform' , {id: @comment.parent_id  , linkid: @comment.link_id}) %>");
    $('#replying_<%= @comment.parent_id%> form').css("float","left");
    $('#Cancel_reply').click(function(){
       $('form[id="new_comment"]').remove();
        $('.errorz').remove();
    });

    $('#new_comment').on("ajax:success", function(event, xhr, settings,data){
        location.reload();
    }).bind("ajax:send",function(){
        $('#Cancel_reply').hide();
        $('.reply_action input[type="submit"]').val('Loading');
        $('.reply_action input[type="submit"]').prop('disabled',true);
    }).bind("ajax:error", function(e,xhr,status,error){
        $('#Cancel_reply').show();
        $('#replying_<%= @comment.parent_id%>').append($('<p> -'+xhr.responseJSON.error+ ' </p>').addClass('errorz'));
        $('.reply_action input[type="submit"]').val('Retry Reply');
        $('.reply_action input[type="submit"]').prop('disabled',false);
    });
});

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', link_path(@comment.link_id) %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "RedditApp", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                    <li><%= link_to 'Submit link', new_link_path %></li>
                    <li><%= link_to 'Account', edit_user_registration_path %></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                <% else %>
                    <li><%= link_to 'Sign up', new_user_registration_path %></li>
                    <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReddApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>
<%= yield %>





</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title ,  :class => 'input' %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url , :class => 'input' %>
  </div>
  <div class="actions">
    <%= f.submit %>
      <%= button_to 'Back to Main', root_url, :method => :get %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<!--<p id="notice"><%= notice %></p>
<table id="linktable">
  <thead>
    <tr>
      <th>Title</th>
      &lt;!&ndash;<th>Url</th>&ndash;&gt;
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @links.each do |link| %>
      <tr>
        <td><a href=<%= link.url %> > <%= link.title %></a></td>
        &lt;!&ndash;<td><%= link.url %></td>&ndash;&gt;
          <td><%= link_to 'Show', link %></td>
       </tr>
    <% end %>

  </tbody>
</table>
<br>-->

<% @links.each do |link| %>
    <div id="linktable" class="link row clearfix">
        <h2>
            <%= link_to link.title, link.url %><br>
            <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%=link.user.name %> </small>
        </h2>
        <div class="btn-group">
            <%= link_to "Comments", link , class: "btn btn-default btn-sm"%>
            <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-chevron-up"></span>
                Upvote
                <%= link.get_upvotes.size %>
            <% end %>
            <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-chevron-down"></span>
                Downvote
            <%= link.get_downvotes.size %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/links/new.html.erb
<h1 class="Headerz">Add a New Link</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<p id="UrlTitle">
  <strong><a href=<%= @link.url %> ><%= @link.title %></a>
     <br> <small>Submitted by <%= @link.user.name %></small>
  </strong>
</p>

<div id="LinkOptions">

    <div class="btn-group">
        <% if @link.user == current_user %>
            <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default btn-sm" %>
            <%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %>
        <% end %>
        <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
            Upvote
            <%= @link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-down"></span>
            Downvote
            <%= @link.get_downvotes.size %>
        <% end %>
        <%= link_to 'Back', links_path , class: "btn btn-default btn-sm"%>
    </div>

</div>

<div class="comments_title pull-left">
    <%= @link.comments.count %> Comments
</div>

<hr>
<p id="main_error">ERRORS</p>
<div id="LinkAlign">
<% if user_signed_in? %>
<%= simple_form_for [@link, Comment.new],html:{id: "main_new_comment"}, remote: true do |f| %>
    <%= f.hidden_field :parent_id %>
    <div class="field">
        <%= f.text_area :body, class: "form-control" %>
    </div>

    <%= f.submit "Add Comment", class: "btn btn-primary" %>
    
        <% end %>
    <%end%>
</div>
<br>
<h3 class="commentz">
    <%= comments_tree_for @link.comments.roots %>
</h3>